name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'

      - name: Install Dependency
        run: npm install --legacy-peer-deps
      - name: Make Plugins
        run: npm run build && npm run copyToDist
      - name: Make DemoPage
        run: npm run demo-wiki

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-dist
